name: Cypress Cloud Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cypress execution
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          # This connects to the Secret you saved in GitHub Settings
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}